// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: public_vote.proto

package public_vote

import (
	context "context"
	election "genprotos/election"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PublicVoteService_CreatePublicVote_FullMethodName  = "/protos.PublicVoteService/CreatePublicVote"
	PublicVoteService_DeletePublicVote_FullMethodName  = "/protos.PublicVoteService/DeletePublicVote"
	PublicVoteService_UpdatePublicVote_FullMethodName  = "/protos.PublicVoteService/UpdatePublicVote"
	PublicVoteService_GetByIdPublicVote_FullMethodName = "/protos.PublicVoteService/GetByIdPublicVote"
	PublicVoteService_GetAllPublucVotes_FullMethodName = "/protos.PublicVoteService/GetAllPublucVotes"
)

// PublicVoteServiceClient is the client API for PublicVoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicVoteServiceClient interface {
	CreatePublicVote(ctx context.Context, in *PublicVote, opts ...grpc.CallOption) (*election.Void, error)
	DeletePublicVote(ctx context.Context, in *election.ById, opts ...grpc.CallOption) (*election.Void, error)
	UpdatePublicVote(ctx context.Context, in *PublicVote, opts ...grpc.CallOption) (*election.Void, error)
	GetByIdPublicVote(ctx context.Context, in *election.ById, opts ...grpc.CallOption) (*PublicVote, error)
	GetAllPublucVotes(ctx context.Context, in *election.Void, opts ...grpc.CallOption) (*GetAllPublicVote, error)
}

type publicVoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicVoteServiceClient(cc grpc.ClientConnInterface) PublicVoteServiceClient {
	return &publicVoteServiceClient{cc}
}

func (c *publicVoteServiceClient) CreatePublicVote(ctx context.Context, in *PublicVote, opts ...grpc.CallOption) (*election.Void, error) {
	out := new(election.Void)
	err := c.cc.Invoke(ctx, PublicVoteService_CreatePublicVote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicVoteServiceClient) DeletePublicVote(ctx context.Context, in *election.ById, opts ...grpc.CallOption) (*election.Void, error) {
	out := new(election.Void)
	err := c.cc.Invoke(ctx, PublicVoteService_DeletePublicVote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicVoteServiceClient) UpdatePublicVote(ctx context.Context, in *PublicVote, opts ...grpc.CallOption) (*election.Void, error) {
	out := new(election.Void)
	err := c.cc.Invoke(ctx, PublicVoteService_UpdatePublicVote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicVoteServiceClient) GetByIdPublicVote(ctx context.Context, in *election.ById, opts ...grpc.CallOption) (*PublicVote, error) {
	out := new(PublicVote)
	err := c.cc.Invoke(ctx, PublicVoteService_GetByIdPublicVote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicVoteServiceClient) GetAllPublucVotes(ctx context.Context, in *election.Void, opts ...grpc.CallOption) (*GetAllPublicVote, error) {
	out := new(GetAllPublicVote)
	err := c.cc.Invoke(ctx, PublicVoteService_GetAllPublucVotes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicVoteServiceServer is the server API for PublicVoteService service.
// All implementations must embed UnimplementedPublicVoteServiceServer
// for forward compatibility
type PublicVoteServiceServer interface {
	CreatePublicVote(context.Context, *PublicVote) (*election.Void, error)
	DeletePublicVote(context.Context, *election.ById) (*election.Void, error)
	UpdatePublicVote(context.Context, *PublicVote) (*election.Void, error)
	GetByIdPublicVote(context.Context, *election.ById) (*PublicVote, error)
	GetAllPublucVotes(context.Context, *election.Void) (*GetAllPublicVote, error)
	mustEmbedUnimplementedPublicVoteServiceServer()
}

// UnimplementedPublicVoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPublicVoteServiceServer struct {
}

func (UnimplementedPublicVoteServiceServer) CreatePublicVote(context.Context, *PublicVote) (*election.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePublicVote not implemented")
}
func (UnimplementedPublicVoteServiceServer) DeletePublicVote(context.Context, *election.ById) (*election.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePublicVote not implemented")
}
func (UnimplementedPublicVoteServiceServer) UpdatePublicVote(context.Context, *PublicVote) (*election.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePublicVote not implemented")
}
func (UnimplementedPublicVoteServiceServer) GetByIdPublicVote(context.Context, *election.ById) (*PublicVote, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIdPublicVote not implemented")
}
func (UnimplementedPublicVoteServiceServer) GetAllPublucVotes(context.Context, *election.Void) (*GetAllPublicVote, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPublucVotes not implemented")
}
func (UnimplementedPublicVoteServiceServer) mustEmbedUnimplementedPublicVoteServiceServer() {}

// UnsafePublicVoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicVoteServiceServer will
// result in compilation errors.
type UnsafePublicVoteServiceServer interface {
	mustEmbedUnimplementedPublicVoteServiceServer()
}

func RegisterPublicVoteServiceServer(s grpc.ServiceRegistrar, srv PublicVoteServiceServer) {
	s.RegisterService(&PublicVoteService_ServiceDesc, srv)
}

func _PublicVoteService_CreatePublicVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).CreatePublicVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_CreatePublicVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).CreatePublicVote(ctx, req.(*PublicVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicVoteService_DeletePublicVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(election.ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).DeletePublicVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_DeletePublicVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).DeletePublicVote(ctx, req.(*election.ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicVoteService_UpdatePublicVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).UpdatePublicVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_UpdatePublicVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).UpdatePublicVote(ctx, req.(*PublicVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicVoteService_GetByIdPublicVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(election.ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).GetByIdPublicVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_GetByIdPublicVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).GetByIdPublicVote(ctx, req.(*election.ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicVoteService_GetAllPublucVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(election.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).GetAllPublucVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_GetAllPublucVotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).GetAllPublucVotes(ctx, req.(*election.Void))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicVoteService_ServiceDesc is the grpc.ServiceDesc for PublicVoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicVoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.PublicVoteService",
	HandlerType: (*PublicVoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePublicVote",
			Handler:    _PublicVoteService_CreatePublicVote_Handler,
		},
		{
			MethodName: "DeletePublicVote",
			Handler:    _PublicVoteService_DeletePublicVote_Handler,
		},
		{
			MethodName: "UpdatePublicVote",
			Handler:    _PublicVoteService_UpdatePublicVote_Handler,
		},
		{
			MethodName: "GetByIdPublicVote",
			Handler:    _PublicVoteService_GetByIdPublicVote_Handler,
		},
		{
			MethodName: "GetAllPublucVotes",
			Handler:    _PublicVoteService_GetAllPublucVotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public_vote.proto",
}
